### Abfrage aller  Kategorien sortiert nach Namen

GET http://localhost:57745/api/categories

### Abfrage einer spezifischen Kategorie

GET http://localhost:57745/api/categories/4


### Abfrage aller Filme eiener Kategorie sortiert nach Namen

GET http://localhost:57745/api/categories/4/movies